language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
branches:
  only:
    - master
    - /^release-.+$/
script: >
  mvn test \
   -Dteavm.test.skip=false \
   -Dteavm.test.selenium="http://$SAUCE_USER_NAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub" \
   -Dteavm.test.threads=2
after_script:
  - rm -rf $HOME/.m2/repository/org/teavm