language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
branches:
  only:
    - master
    - /^release-.+$/
env:
  - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
script: >
  mvn -e test \
   -Dteavm.junit.target=target/js-tests \
   -Dteavm.junit.js.runner=htmlunit \
   -Dteavm.junit.js.threads=1
after_script:
  - rm -rf $HOME/.m2/repository/org/teavm